// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm-mqtxmjLPII2hB1QAvRQlhDBrdUFF7A',
    appId: '1:854435803640:web:e55352cccb5cf7d91be60d',
    messagingSenderId: '854435803640',
    projectId: 'republicday-7de92',
    authDomain: 'republicday-7de92.firebaseapp.com',
    storageBucket: 'republicday-7de92.appspot.com',
    measurementId: 'G-5K11881GT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBToNOGYzHvs5wG-3RhQKRQja1CLsFBcGM',
    appId: '1:854435803640:android:4641b44b6e77aeca1be60d',
    messagingSenderId: '854435803640',
    projectId: 'republicday-7de92',
    storageBucket: 'republicday-7de92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu2rtXspb3k18ha1CaifIF5Q4yQaPhNWQ',
    appId: '1:854435803640:ios:f38703358d73e4311be60d',
    messagingSenderId: '854435803640',
    projectId: 'republicday-7de92',
    storageBucket: 'republicday-7de92.appspot.com',
    iosClientId: '854435803640-trif7vrvra33o9ks3mtesraufp087lid.apps.googleusercontent.com',
    iosBundleId: 'com.example.republicDayFinal',
  );
}
